set(HEADERS
    ${HEADERS}
    include/engine/graphics/buffer.h
    include/engine/graphics/bufferwriter.h
    include/engine/graphics/color.h
    include/engine/graphics/colorgradient.h
    include/engine/graphics/image.h
    include/engine/graphics/matrix.h
    include/engine/graphics/transform.h
    include/engine/graphics/renderer.h
    include/engine/graphics/vector2d.h
    include/engine/graphics/vertex2d.h
)

set(SOURCES
    ${SOURCES}
    graphics/bufferwriter.cpp
    graphics/color.cpp
    graphics/colorgradient.cpp
    graphics/image.cpp
    graphics/renderer.cpp
    graphics/vector2d.cpp
    graphics/vertex2d.cpp
) 
